Changed Keeps only the most recent package

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -588,33 +588,72 @@ runs:
       if: inputs.update_db == 'true' && success()
       shell: bash
       run: |
+        # Function to send Telegram message
+        send_telegram_message() {
+          message="$1"
+          curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
+            -d chat_id="${{ inputs.telegram_chat_id }}" \
+            -d text="$message" \
+            -d parse_mode="MarkdownV2"
+        }
+
+        # Determine the branch based on the branch type
+        if [ "${{ inputs.branch_type }}" == "stable" ]; then
+          branch="STABLE"
+          db_name="community-stable"
+        elif [ "${{ inputs.branch_type }}" == "aur" ] || [ "${{ inputs.branch_type }}" == "testing" ]; then
+          branch="TESTING"
+          db_name="community-testing"
+        else
+          echo "Error: Unknown branch type: ${{ inputs.branch_type }}"
+          exit 1
+        fi
+
+        echo "Branch: $branch"
+        echo "Database name: $db_name"
+
+        branch_escaped=$(echo "$branch" | sed 's/[_*[\]()~`>#+\-=|{}.!]/\\&/g')
+
+        echo "🧹 Limpando pacotes antigos no repositório $branch..."
+        send_telegram_message "🧹 **Iniciando limpeza de pacotes antigos no repositório** \`$branch_escaped\`"
+
         ssh ${{ inputs.repo_user }}@${{ inputs.repo_host }} -p ${{ inputs.repo_port }} << EOF
           set -x
           cd ${{ inputs.repo_dir }}/${branch,,}/x86_64
+          
+          # Mantenha apenas a versão mais recente de cada pacote
           paccache -rk1
-          echo "Comando paccache concluído com código de saída: \$?"
+          
+          # Remova todos os pacotes que não estão no banco de dados
+          repo-remove $db_name.db.tar.gz \$(comm -23 <(ls *.pkg.tar.zst | sort) <(tar -tf $db_name.db.tar.gz | grep -v '/$' | sed 's|-[^-]*-[^-]*$||' | sort -u))
+          
+          # Remova os arquivos .md5 e .sig órfãos
+          find . -name "*.md5" -or -name "*.sig" | while read file; do
+            pkg_name=\$(basename "\$file" | sed 's/\.[^.]*$//')
+            if [ ! -f "\${pkg_name}.pkg.tar.zst" ]; then
+              rm "\$file"
+            fi
+          done
+          
+          exit_code=\$?
+          echo "Comando paccache concluído com código de saída: \$exit_code"
+          exit \$exit_code
         EOF
 
-
-    # Check Build Status
-    - name: Check Build Status
-      id: check_status
-      if: always()
-      shell: bash 
-      run: |
-        if [ ${{ job.status }} == 'success' ]; then
-          echo "build_status=success" >> $GITHUB_OUTPUT
+        if [ $? -eq 0 ]; then
+          echo "✅ Limpeza de pacotes antigos concluída com sucesso!"
+          send_telegram_message "✅ **Limpeza de pacotes antigos no repositório** \`$branch_escaped\` **concluída com sucesso\!**"
         else
-          echo "build_status=failure" >> $GITHUB_OUTPUT
+          echo "❌ Falha na limpeza de pacotes antigos."
+          send_telegram_message "❌ **Falha na limpeza de pacotes antigos no repositório** \`$branch_escaped\`\."
         fi
+
 
     # Send a Telegram alert if the build fails
     - name: Telegram Alert Fail
       if: failure()
       shell: bash
       run: |
-        if [ "${{ steps.check_status.outputs.build_status }}" == "failure" ]; then
-          curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
-            -d chat_id="${{ inputs.telegram_chat_id }}" \
-            -d text="🚨 FALHA ao criar Pacote: ${{ github.event.action }} a partir do branch ${{ github.ref_name }}, link do erro: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} 🖥"
-        fi
+        curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
+          -d chat_id="${{ inputs.telegram_chat_id }}" \
+          -d text="🚨 FALHA ao criar Pacote Community: ${{ github.event.action }} a partir do branch ${{ github.ref_name }}, link do erro: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} 🖥"
