Add release in packages

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -114,40 +114,117 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Define the function send_telegram_message
+    - name: Definir a função send_telegram_message no script temporário
       shell: bash
       env:
         TELEGRAM_TOKEN: "${{ inputs.telegram_token }}"
         TELEGRAM_CHAT_ID: "${{ inputs.telegram_chat_id }}"
       run: |
-        # Define the function send_telegram_message in the temporary script
+        #Definir a função send_telegram_message no script temporário
         cat << 'EOF' > /tmp/send_telegram_message.sh
+        export TERM=${TERM:-xterm}
+        export TERM=${TERM:-xterm-256color}
 
-        # Defining color variables
-        export bold="\033[1m"
-        export green="\033[01;32m"
+        #Definindo variáveis de cores
         export red="\033[01;31m"
-        export blue="\033[01;34m"
-        export cyan="\033[01;36m"
-        export pink="\033[01;35m"
+        export green="\033[01;32m"
         export yellow="\033[01;33m"
-        export std="\033[0m"
-        
+        export blue="\033[01;34m"
+        export pink="\033[01;35m"
+        export cyan="\033[01;36m"
+        export reset="\033[0m"
+        alias ls='ls -lha --color=auto'
+        alias dir='ls -lha --color=auto'
+
+        die() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${cyan}error: ${red}${msg}${reset}"
+          exit  1
+        }
+        export -f die
+
+        msg_raw() {
+          local msg="$1"
+          # Remove tags HTML, se existirem
+          #msg="$(sed 's/<[^>]*>//g' <<< "$msg")"
+
+          # Verifica se existe ':' na mensagem
+          if [[ "$msg" == *:* ]]; then
+            # Divide a string antes e depois do primeiro ':'
+            local before_colon="${msg%%:*}:"
+            local after_colon="${msg#*: }"
+            # Aplica as cores
+            msg="${cyan}${before_colon} ${red}${after_colon}${reset}"
+          else
+            # Se não houver ':', aplica apenas a cor padrão
+            msg="${cyan}${msg}${reset}"
+          fi
+          echo -e "$msg"
+        }
+        export -f msg_raw
+
+        msg() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${cyan}running: ${yellow}${msg}${reset}"
+        }
+        export -f msg
+
+        msg_ok() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${cyan}feito: ${green}${msg}${reset}"
+        }
+        export -f msg_ok
+
+        msg_run() {
+          local msg="$1"
+          echo -e "BP=>${cyan}running: ${yellow}${msg}${reset}"
+          eval "$msg"
+        }
+        export -f msg_run
+
+        msg_info() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${yellow}info   : ${cyan}${msg}${reset}"
+        }
+        export -f msg_info
+
+        msg_warning() {
+          local msg="$1"
+          msg="$(sed 's/<[^>]*>//g' <<< "$msg")" # Remove as tags HTML
+          echo -e "BP=>${red}warning: ${orange}${msg}${reset}"
+        }
+        export -f msg_warning
+
+        replicate() {
+          local char=${1:-'#'}
+          local nsize=${2:-$(tput cols)}
+          local line
+          #printf -v line "%*s" "$nsize" && echo "${line// /$char}"
+          #printf -v line "%*s" "$nsize" && echo -e "\033[31m${line// /$char}\033[0m"
+          printf -v line "%*s" "$nsize" && echo -e "${blue}${line// /$char}${reset}"
+        }
+        export -f replicate
+
         send_telegram_message() {
           local message="$1"
           local parse_mode="$2"
 
-          # Define parse_mode as "MarkdownV2" if not specified
+          # Define parse_mode como "MarkdownV2" se não for especificado
           [[ -z $parse_mode ]] && parse_mode="HTML"
 
-          # Remove the HTML tags and display the result in the terminal
+          # Remove as tags HTML e exibe o resultado no terminal
           echo -e "${red}$(sed 's/<[^>]*>//g' <<< "$message")${reset}"
-          # Send the original message with HTML to Telegram
+          # Envia a mensagem original com HTML para o Telegram
           curl -s -X POST "https://api.telegram.org/bot${{ inputs.telegram_token }}/sendMessage" \
             -d chat_id="${{ inputs.telegram_chat_id }}" \
             -d text="$message" \
             -d parse_mode="$parse_mode"
         }
+        export -f send_telegram_message
         EOF
 
     - name: Initializing package creation
@@ -389,9 +466,11 @@ runs:
 
           # Extract dependencies from PKGBUILD
           source PKGBUILD
-          echo "Debug: Loading dependencies from the PKGBUILD..."
-          echo "depends: ${depends[@]}"
-          echo "makedepends: ${makedepends[@]}"
+          TAG_NAME="$pkgver-$pkgrel"
+          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
+          msg_info "TAG_NAME   : ${TAG_NAME}"
+          msg_info "depends    : ${depends[@]}"
+          msg_info "makedepends: ${makedepends[@]}"
 
           # Install all dependencies using yay
           install_dependencies() {
@@ -424,6 +503,12 @@ runs:
           # Para pacotes não-AUR
           gitfolder=$(find -type f -name PKGBUILD | sed 's/PKGBUILD//')
           cd $gitfolder
+          source PKGBUILD
+          TAG_NAME="$pkgver-$pkgrel"
+          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
+          msg_info "TAG_NAME   : ${TAG_NAME}"
+          msg_info "depends    : ${depends[@]}"
+          msg_info "makedepends: ${makedepends[@]}"
 
           # Ensure architecture is set to x86_64
           sed -i "/^arch=/c\arch=('x86_64')" PKGBUILD
@@ -628,6 +713,9 @@ runs:
           pkgname=$(basename "$i")
           pkgname_escaped=$(echo "$pkgname" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')
           branch_escaped=$(echo "$branch" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')
+          echo "PKGNAME_BASENAME=$pkgname_escaped"  >> $GITHUB_ENV
+          echo "PKGNAME_BRANCH=${branch_escaped,,}" >> $GITHUB_ENV
+          repo_path="${{ inputs.repo_dir }}"
           repositorio="${{ inputs.repo_dir }}"
           file_size_bytes=$(stat -c%s "$i")
           file_size_kb=$((file_size_bytes / 1024))
@@ -777,6 +865,116 @@ runs:
           send_telegram_message "$message"
         fi
 
+    - name: Extrair data do nome do arquivo .zst e definir tag_name
+      if: ${{ inputs.teste_input != true }}
+      id: set-tag-name
+      shell: bash
+      run: |
+        #Extrair data do nome do arquivo .zst e definir tag_name
+        source /tmp/send_telegram_message.sh
+        replicate '#'
+        FILENAME="${{env.PKGNAME_BASENAME}}"
+        TAG_NAME="${{env.TAG_NAME}}"
+        echo "PKG_TAG_NAME=$TAG_NAME"                            >> $GITHUB_ENV
+        echo "pkg_path=/home/packages/${{env.PKGNAME_BASENAME}}" >> $GITHUB_OUTPUT
+        echo "PKG_PATH=/home/packages/${{env.PKGNAME_BASENAME}}" >> $GITHUB_ENV
+
+        msg_raw "FILENAME    : ${{env.PKGNAME_BASENAME}}"
+        msg_raw "TAG_NAME    : ${{env.TAG_NAME}}"
+        msg_raw "PKG_TAG_NAME: $TAG_NAME"
+        msg_raw "pkg_path    : /home/packages/${{env.PKGNAME_BASENAME}}"
+        msg_raw "PKG_PATH    : /home/packages/${{env.PKGNAME_BASENAME}}"
+        replicate '#'
+
+    - name: Prepare Package for release (7z)
+      id: prepare-package
+      shell: bash
+      run: |
+        #Prepare Package for release (7z)
+        source /tmp/send_telegram_message.sh
+        replicate '#'
+        pushd /home/packages || true
+        # Prepara a mensagem
+        message="⏳ <b>[step 3/4] build-package - Prepare Package for release (7z)</b>
+        <b>Job:</b> <code>#${GITHUB_RUN_NUMBER}</code>
+        <b>Workflow:</b> <code>build-package/action.yml</code>
+        <b>Pacote:</b> <code>${{ env.PKGNAME_BRANCH }}/${{ env.PKGNAME_BASENAME }}</code>
+        <b>Inicio:</b> <code>${START_TIME}</code>"
+        send_telegram_message "$message"
+        msg_info "$message"
+        replicate '-'
+        msg_run "ls -lah $PWD"
+        release=$(basename "${{env.PKG_PATH}}" .pkg.tar.zst)
+        release_name="${release}"
+
+        # Obtém o tamanho do arquivo em bytes
+        file_size=$(stat -c%s "${{env.PKG_PATH}}")
+
+        # Verifica se o tamanho é maior que 2000 MB (2000 * 1024 * 1024 bytes)
+        if (( file_size > 2000 * 1024 * 1024 )); then
+          msg_info "O arquivo é maior que 2000 MB. Compactando e dividindo..."
+          7z a -v2000m "${release}.7z" "${{env.PKG_PATH}}" # Compacta e divide em partes de 2000 MB
+          upload_path="${release}.7z*"
+        else
+          msg_info "O arquivo não é maior que 2000 MB. Não será compactado."
+          upload_path="${{env.PKG_PATH}}"
+        fi
+
+        echo "release=${release}"         >> "$GITHUB_OUTPUT"
+        echo "release_name=${release}"    >> "$GITHUB_OUTPUT"
+        echo "upload_path=${upload_path}" >> "$GITHUB_OUTPUT"
+
+        msg_info "Package ${release} prepared for release"
+        replicate '-'
+        msg_run "ls -lah $PWD"
+        replicate '-'
+        # Debug
+        msg_info "full_pkgname (original): ${{env.PKG_PATH}}"
+        msg_info "Upload Path            : ${upload_path}"
+        msg_info "full_pkgname (sig)     : ${{env.PKG_PATH}}.sig"
+        msg_info "full_pkgname (md5)     : ${{env.PKG_PATH}}.md5"
+        msg_info "full_pkgname (sig.md5) : ${{env.PKG_PATH}}.sig.md5"
+        msg_info "release                : ${release}"
+        msg_info "release_name           : ${release_name}"
+        popd || true
+        replicate '='
+
+    - name: Verificar se o package foi gerado corretamente
+      if: ${{ inputs.teste_input != true }}
+      shell: bash
+      run: |
+        # Verificar se o arquivo package foi gerado corretamente
+        source /tmp/send_telegram_message.sh
+        replicate '='
+        pushd /home/packages || true
+        msg_run 'ls -lah --color=auto $PWD'
+        popd || true
+        replicate '='
+
+    - name: Create Release
+      if: ${{ inputs.teste_input != true }}
+      id: create_release
+      uses: softprops/action-gh-release@v1
+      with:
+        files: |
+          ${{ env.PKG_PATH }}.sig
+          ${{ env.PKG_PATH }}.md5
+          ${{ env.PKG_PATH }}.sig.md5
+          ${{ steps.prepare-package.outputs.upload_path }}
+        tag_name: ${{ env.PKG_TAG_NAME }}
+        name: ${{ steps.prepare-package.outputs.release_name }}
+        generate_release_notes: true
+        body: |
+          - **Data e Hora        :** ${{ env.START_TIME }}
+          - **Arquivo PKG        :** ${{ env.PKGNAME_BASENAME }}
+          - **Arquivo SIG        :** ${{ env.PKGNAME_BASENAME }}.sig
+          - **Arquivo MD5        :** ${{ env.PKGNAME_BASENAME }}.md5
+          - **Arquivo SIG.MD5    :** ${{ env.PKGNAME_BASENAME }}.sig.md5
+          - **Nome do Repositório:** ${{ env.REPO_NAME }}
+        draft: false
+        prerelease: false
+        fail_on_unmatched_files: false
+  
     # Send a Telegram alert if the build fails
     - name: Telegram Alert Fail
       if: failure()
